name: lamport

on:
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE-APACHE
      - LICENSE-MIT
  push:
    branches: main
    paths-ignore:
      - README.md
      - LICENSE-APACHE
      - LICENSE-MIT

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_LOG_STYLE: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo test --all-features

  careful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo bininstall cargo-careful
      - run: cargo careful --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@smaster
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all-features -- --check

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
      - run: cargo doc --all-features

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo bininstall cargo-udeps
      - run: cargo udeps --all-targets --all-features

  outdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo bininstall cargo-outdated
      - run: cargo outdated --root-deps-only --exit-code=1

  pants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo bininstall cargo-pants
      - run: cargo pants --loud --dev